### ISSUE TITLE
 how to write string in HDF5 file? datatype(String) not works .

### ISSUE THREAD

**Issue by programistawpf** [JuliaIO/HDF5.jl#461] opened 2018-01-20 13:02 UTC
julia> fid = h5open("file.h5","r+")
HDF5 data file: file.h5

julia> g = fid["/"]
HDF5 group: / (file: file.h5)
julia> dset = d_create(g, "F", datatype(String), dataspace(nol,cnt))
ERROR: MethodError: no method matching datatype(::Type{String})
Closest candidates are:
  datatype(::HDF5.HDF5Attribute) at C:\Users\PC\.julia\v0.6\HDF5\src\HDF5.jl:1125
  datatype(::HDF5.HDF5Dataset) at C:\Users\PC\.julia\v0.6\HDF5\src\HDF5.jl:1123
  datatype(::T<:Union{Float32, Float64, HDF5.HDF5ReferenceObj, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt
) where T<:Union{Float32, Float64, HDF5.HDF5ReferenceObj, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, U
:\Users\PC\.julia\v0.6\HDF5\src\HDF5.jl:1128
  ...

**Comment by musm** [comment] 2020-12-07 21:03
See documentation or `plain.jl` on how to write strings. 

This issue on the other hand is a dupe of https://github.com/JuliaIO/HDF5.jl/issues/336

**Closed by musm** 2020-12-07 21:03 UTC
