### ISSUE TITLE
Couldn't use user specified HDF5 library after v0.12.0

### ISSUE THREAD

**Issue by ziyixi** [JuliaIO/HDF5.jl#567] opened 2019-08-16 14:24 UTC
Hello,

According to my test, after v0.12.0, I couldn't specify my own HDF5 library. (It's useful since in some platform we might have to compile our own parallel version of HDF5) Details are described in #566 This issue only occurs after v0.12.0 as #555 in v0.12.0 updates the `build.jl`.

**Comment by ziyixi** [comment] 2019-08-16 14:46
This issue should be related to #562

**Comment by musm** [comment] 2019-08-21 15:39
yes duplicate of #562

**Closed by musm** 2019-08-21 15:39 UTC
