### ISSUE TITLE
can not use HDF5. error with libblosc

### ISSUE THREAD

**Issue by jingpengw** [JuliaIO/HDF5.jl#234] opened 2015-05-09 20:52 UTC
ubuntu 14.04, julia V0.3

julia> using HDF5
Warning: error initializing module Blosc:
ErrorException("error compiling **init**: could not load module /usr/people/jingpeng/.julia/v0.3/Blosc/src/../deps/libblosc: /usr/people/jingpeng/.julia/v0.3/Blosc/src/../deps/libblosc: cannot open shared object file: No such file or directory")

ERROR: error compiling blosc_filter: could not load module /usr/people/jingpeng/.julia/v0.3/Blosc/src/../deps/libblosc: /usr/people/jingpeng/.julia/v0.3/Blosc/src/../deps/libblosc: cannot open shared object file: No such file or directory
 in register_blosc at /usr/people/jingpeng/.julia/v0.3/HDF5/src/blosc_filter.jl:123
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /usr/people/jingpeng/.julia/v0.3/HDF5/src/plain.jl, in expression starting on line 510
while loading /usr/people/jingpeng/.julia/v0.3/HDF5/src/HDF5.jl, in expression starting on line 1

**Comment by rened** [comment] 2015-05-10 19:57
Can you try to run `Pkg.build("Blosc")` and see whether that succeeds?

**Comment by jingpengwu** [comment] 2015-05-12 18:56
thanks for the reply.
It seems that it is a bug of Blosc. I can not build Blosc.

julia> Pkg.build("Blosc")
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===========================================================================================================[
ERROR: Blosc
]============================================================================================================

failed process: Process(`curl -f -o c-blosc-1.5.0.tar.gz -L
https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77))
[77]
while loading /usr/people/jingpeng/.julia/v0.3/Blosc/deps/build.jl, in
expression starting on line 17

=======================================================================================================================================================================================================================================

===========================================================================================================[
BUILD ERRORS
]============================================================================================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in
/usr/people/jingpeng/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================================================================================================================================================================

**Comment by jingpengwu** [comment] 2015-05-12 18:58
$ julia build.jl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
ERROR: failed process: Process(`curl -f -o c-blosc-1.5.0.tar.gz -L
https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77))
[77]
 in pipeline_error at process.jl:502
 in run at ./process.jl:479
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /usr/people/jingpeng/.julia/v0.3/Blosc/deps/build.jl, in
expression starting on line 17

**Comment by stevengj** [comment] 2015-05-12 20:09
The `curl` command to download Blosc is failing.  Are you behind a firewall or something?

**Comment by rened** [comment] 2015-05-12 20:10
Could you please try to run `Pkg.update()` and then try again with `Pkg.build("Blosc")` - the URL does not exist any more (404).

**Comment by simonster** [comment] 2015-05-12 20:17
@rened The URL https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz exists, but it's getting auto-linked with the final backtick.

Based on the error, it looks like the problem is that `curl` on your system is misconfigured. Something is wrong with the CA bundle, so `curl` refuses to use SSL because it can't authenticate the connection. Does `/etc/pki/tls/certs/ca-bundle.crt` exist on your system? If not, you (or your system administrator) will need to figure out how to install the CA bundle so that `curl` can find it.

**Comment by jingpengwu** [comment] 2015-05-12 20:18
Yes, I am in princeton university, which probably have a firewall. However,
I have not find other links that I can not access.

I tried again, it failed.
Actually, my laptop have a working julia HDF5, which was build outside the
university!

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Docile...
INFO: Updating cache of Compose...
INFO: Updating cache of HDF5...
INFO: Updating cache of Gadfly...
INFO: Computing changes...
INFO: Upgrading Compose: v0.3.11 => v0.3.12
INFO: Upgrading Docile: v0.4.12 => v0.4.13
INFO: Upgrading Gadfly: v0.3.11 => v0.3.12
INFO: Upgrading HDF5: v0.4.15 => v0.4.16
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===========================================================================================================[
ERROR: Blosc
]============================================================================================================

failed process: Process(`curl -f -o c-blosc-1.5.0.tar.gz -L
https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77))
[77]
while loading /usr/people/jingpeng/.julia/v0.3/Blosc/deps/build.jl, in
expression starting on line 17

=======================================================================================================================================================================================================================================
INFO: Building HDF5

===========================================================================================================[
BUILD ERRORS
]============================================================================================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in
/usr/people/jingpeng/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================================================================================================================================================================

julia> Pkg.build("Blosc")
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===============================================================================================================[
ERROR: Blosc
]================================================================================================================

failed process: Process(`curl -f -o c-blosc-1.5.0.tar.gz -L
https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77))
[77]
while loading /usr/people/jingpeng/.julia/v0.3/Blosc/deps/build.jl, in
expression starting on line 17

===============================================================================================================================================================================================================================================

===============================================================================================================[
BUILD ERRORS
]================================================================================================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in
/usr/people/jingpeng/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================================================================================================================================================

**Comment by rened** [comment] 2015-05-12 20:21
@simonster ah, you are right of course... I first went after the CA issue, then thought it was just the URL...

**Comment by jingpengwu** [comment] 2015-05-18 19:46
I have fixed it by modifying the BinDeps.jl !

I add a "-k" option for curl.

return `curl -f -k -o $filename -L $url`

than I rebuild the Blosc

julia> Pkg.build("Blosc")
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100   121    0   121    0     0   1503      0 --:--:-- --:--:-- --:--:--
1920
100  233k  100  233k    0     0   903k      0 --:--:-- --:--:-- --:--:--
2290k
Compiling libblosc...
   CC blosc.c
   CC blosclz.c
   CC shuffle.c
   LINK libblosc

**Comment by bjarthur** [comment] 2015-06-18 21:08
i had similar problems that were fixed by nuking ~/.julia/v0.3

**Comment by stevengj** [comment] 2015-06-24 18:16
Should there be a BinDeps issue to add a way to use `curl -k`?  i.e. make `download_cmd(url::String, filename::String)` take an optional `insecure::Bool=false` argument?

**Comment by ewiger** [comment] 2015-06-25 20:47
Solution is to tell your curl where to find CA bundle:

```
# fix CURL certificates path
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

http://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url/31060428#31060428

**Comment by musm** [comment] 2019-07-06 04:36
Stale issue. Post back if still a problem.

**Closed by musm** 2019-07-06 04:36 UTC
