### ISSUE TITLE
Performance Issue when closing HDF5.jl

### ISSUE THREAD

**Issue by tknopp** [JuliaIO/HDF5.jl#413] opened 2017-06-04 09:01 UTC
Hi, I have a little strange perfromance issue. In my package https://github.com/MagneticParticleImaging/MPIFiles.jl
I have written unit tests (`Pkg.test("MPIFiles")`) and when the test is already done Julia seems to freeze. It requires more than 10 seconds to finish. If I press Ctrl-C I get a backtrace from within `H5_term_library`. Anybody an idea whats going on here and how to prevent it?

```
julia> Pkg.test("MPIFiles")
INFO: Testing MPIFiles
Test MDF v1: measurement_V1.mdf
Loading measurement from measurement_V1.mdf ...100% Time: 0:00:03
Loading measurement from measurement_V1.mdf ...100% Time: 0:00:10
Loading measurement from measurement_V1.mdf ...100% Time: 0:00:08
Test MDF v2: measurement_V2.mdf
Loading measurement from measurement_V2.mdf ...100% Time: 0:00:09
Loading measurement from measurement_V2.mdf ...100% Time: 0:00:08
Test MDF v1: systemMatrix_V1.mdf
Test MDF v2: systemMatrix_V2.mdf
The unit tests are done!
^C
signal (2): Interrupt: 2
while loading no file, in expression starting on line 0
H5SL_search at /usr/local/lib/libhdf5.dylib (unknown line)
H5I__find_id at /usr/local/lib/libhdf5.dylib (unknown line)
H5I_object at /usr/local/lib/libhdf5.dylib (unknown line)
H5P_facc_close at /usr/local/lib/libhdf5.dylib (unknown line)
H5P_close at /usr/local/lib/libhdf5.dylib (unknown line)
H5I__clear_type_cb at /usr/local/lib/libhdf5.dylib (unknown line)
H5SL_try_free_safe at /usr/local/lib/libhdf5.dylib (unknown line)
H5I_clear_type at /usr/local/lib/libhdf5.dylib (unknown line)
H5P_term_interface at /usr/local/lib/libhdf5.dylib (unknown line)
H5_term_library at /usr/local/lib/libhdf5.dylib (unknown line)
__cxa_finalize_ranges at /usr/lib/system/libsystem_c.dylib (unknown line)
exit at /usr/lib/system/libsystem_c.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 17693287 (Pool: 17601873; Big: 91414); GC: 138
```

**Comment by tknopp** [comment] 2017-06-04 10:33
seems to be caused by the finalizers.

**Comment by tknopp** [comment] 2017-06-04 11:03
It seems that one should not call `h5read` a lot of time. Is this "accumulation" of finalizers expected?

**Comment by tknopp** [comment] 2017-06-04 13:47
Reduced test case:
```
julia> using HDF5

julia> h5write("test2.h5","/test",rand(10,10,10))

julia> for a=1:100000
         h5read("test2.h5","/test")
       end

julia> exit()
```

reasding the dataset requires some time but the call to exit still runs while I am writing this.

**Comment by ggggggggg** [comment] 2017-06-05 23:12
I can't reproduce this. I do 
```
for a=1:100000
         h5read("test2.h5","/test")
       end
```
which takes about 30-60 seconds. Then I do `exit()` and it is nearly instantaneous, less than 1 second.

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
I'm on `HDF5.jl` commit 4ec51b0.

**Comment by tknopp** [comment] 2017-06-06 05:52
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by tknopp** [comment] 2017-06-06 05:56
problem remains. I am on HDF.jl master

**Comment by tknopp** [comment] 2017-06-06 09:05
Have tested this on a Linux box as well and still looks the same:
```
Julia Version 0.5.3-pre+5
Commit c3b8ad0* (2017-05-16 09:15 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by IlyaOrson** [comment] 2017-07-02 04:49
I can reproduce this with the test case.
```julia
julia> versioninfo()
Julia Version 0.6.1-pre.0
Commit dcf39a1dda (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
julia> Pkg.status("HDF5")
 - HDF5                          0.8.1
```

**Comment by musm** [comment] 2017-07-02 05:14
I can't reproduce this either  using the reduced test case
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

```

and using master of HDF5

**Comment by tknopp** [comment] 2017-07-02 13:18
On 0.6 with HDF5 master on OSX, the problem still remains. @musm: You are using windows. Do you have some other OS available to test?

@timholy: We have very different experiences here. Could you add another datapoint?

**Comment by musm** [comment] 2017-07-02 17:52
@tknopp  I also just tested a linux machine  I can reproduce the problem on linux, but not on windows. 
I'm guessing this is related to finalizers

**Comment by musm** [comment] 2017-07-02 18:00
What you can do is
```julia

fid = h5open(filename, "r")
for a=1:100000
    dat = read(fid, "/test")
end
close(fid)

```
which works without any perf issues and is much faster at reading

**Comment by musm** [comment] 2017-07-02 18:03
I'm not sure why it hangs `exit()`

But you can see in the code for `h5read`  what you are doing is really slow. At each loop it opens the handle anew and then tries to close it
```
function h5read(filename, name::String)
    local dat
    fid = h5open(filename, "r")
    try
        dat = read(fid, name)
    finally
        close(fid)
    end
    dat
end
```

**Comment by tknopp** [comment] 2017-07-02 18:08
yes, I know that and now use such an approach. But still the underlying performance issue is still worth investigating. Especially if it does not occur on Windows.

**Comment by colintbowers** [comment] 2017-10-30 02:25
So it turns out I spotted this issue about 3 years and spoke to tim holy about it [on StackOverflow](https://stackoverflow.com/questions/24718476/gradual-slowdown-of-h5write-function-in-julia-hdf5-package) (but completely forgot about it until now). A Python user commented there that they observed a similar issue in h5py, so this lends credence to the assertion that the issue is in the HDF5 C-library. 

However, I did just notice one small anomaly: the problem appears to be worse in Julia v0.6 than in v0.5. I noticed this anecdotally with my own work, but just put together the following (basic) test:

```
using HDF5
numfile = 2000000
temp_h5_filepath(n::Int) = "/home/colin/Temp/hdf5test$(n).h5"
temp_h5_loc() = "G1/D1"
function f()
    println("Building files")
    for n = 1:numfile
        h5write(temp_h5_filepath(n), temp_h5_loc(), randn(3))
    end
    println("Reading files")
    for n = 1:numfile
        x = h5read(temp_h5_filepath(n), temp_h5_loc())
    end
    println("Removing files")
    for n = 1:numfile
        rm(temp_h5_filepath(n))
    end
end
f()
```
On Julia v0.5, I did two timings of a `quit()` call after running the above code, and got:
7.1 seconds
7.5 seconds

On Julia v0.6, the timings were
13.2 seconds
12.2 seconds

I'm not sure how much this helps, since it may just reflect a difference in garbage collection between v0.5 and v0.6, but thought I would post it anyway just in case it prompts something in another users brain.

**Comment by musm** [comment] 2020-12-07 21:23
Sorry to bump up an old thread, is this still a problem? Doesn't sound like it?

**Comment by musm** [comment] 2020-12-09 06:12
If this crops up again, please reopen a new issue. Closing as stale for now.

**Closed by musm** 2020-12-09 06:12 UTC

**Comment by tknopp** [comment] 2020-12-09 07:59
This is fine from my side. My solution was to cache the HDF5 type and not create it over and over again.
