### ISSUE TITLE
define keys instead of (or as well as) names

### ISSUE THREAD

**Issue by rafaqz** [JuliaIO/HDF5.jl#590] opened 2019-10-17 11:22 UTC
`keys` is the general method for returning a list of keys in julia, such as for NamedTuple or Dict.

We should add a `Base.keys` method for datasets and depreciate `names`.

**Comment by musm** [comment] 2020-08-04 06:33
Makes sense

**Comment by musm** [comment] 2020-08-25 15:48
What other methods should we define `keys` makes sense?

Does it make sense to support a dict like interface

**Comment by musm** [comment] 2020-08-25 15:49
duplicate of https://github.com/JuliaIO/HDF5.jl/issues/590

**Closed** 2020-10-09 18:33 UTC
