### ISSUE TITLE
Permit reading values into a preexisting array buffer

### ISSUE THREAD

**Issue by rafaqz** [JuliaIO/HDF5.jl#580] opened 2019-08-28 06:59 UTC
Is there a way of reading from hdf5 directly into a preexisting array buffer? 

Edit: It would also be useful to expose a version of `getindex` or ` copyto!` or something for retrieving part of an array - that let you pass in the dest array instead of [allocating it every time](https://github.com/JuliaIO/HDF5.jl/blob/master/src/HDF5.jl#L1781).

**Comment by Luapulu** [comment] 2020-11-02 01:10
I’d be interested in this, too.

**Comment by musm** [comment] 2020-12-07 21:17
dupe of https://github.com/JuliaIO/HDF5.jl/issues/409

**Closed** 2022-06-07 20:50 UTC
Labels: enhancement
