### ISSUE TITLE
PyCall - HDF5 clash: load ordering

### ISSUE THREAD

**Issue by zyth0s** [JuliaIO/HDF5.jl#702] opened 2020-10-12 15:44 UTC
The following terminates Julia's session:
```julia
# Activate conda 'base' environment with
ENV["PYTHON"] = joinpath(ENV["HOME"], "miniconda3/bin/python")
using Pkg; Pkg.build("PyCall")

# Relaunch Julia

using PyCall: pyimport
# PySCF is installed in conda 'base' environment
using HDF5
pyscf = pyimport("pyscf") # -> Terminates
# If all pyimports are placed before using HDF5 => fine

# Content of ~/.julia/config/startup.jl (does not affect anything)
# After activating virtual environment in the system shell
ENV["PYCALL_JL_RUNTIME_PYTHON"] = Sys.which("python")
```
My problem is that I need to set the module "pyscf" as a global variable
in a package and at the same time I need HDF5 whithin the module. 
I can not delay the import of HDF5.

```julia
(@v1.5) pkg> st HDF5 PyCall
Status `~/.julia/environments/v1.5/Project.toml`
  [f67ccb44] HDF5 v0.13.6
  [438e738f] PyCall v1.92.0
```

```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 1
  JULIA_EDITOR = view
```

**Comment by jmert** [comment] 2020-10-12 16:29
"Terminates" how? Is it a segfault, julia just seems to quit, something else, ...? I don't use Anaconda, but a pip-installed `pyscf` with Arch's `python` worked fine for me:
```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 3 2200G with Radeon Vega Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)

julia> using PyCall: pyimport

julia> using HDF5

julia> pyscf = pyimport("pyscf")
PyObject <module 'pyscf' from '/home/justin/.local/lib/python3.8/site-packages/pyscf/__init__.py'>

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [f67ccb44] HDF5 v0.13.6
  [438e738f] PyCall v1.92.1
...
```

**Comment by zyth0s** [comment] 2020-10-12 16:40
The error message is:

```
ERROR: LoadError: PyError (PyImport_ImportModule

The Python package pyscf could not be imported by pyimport. Usually this means
that you did not install pyscf in the Python version being used by PyCall.

PyCall is currently configured to use the Python version at:

/Users/daniel/miniconda3/bin/python

and you should use whatever mechanism you usually use (apt-get, pip, conda,
etcetera) to install the Python package containing the pyscf module.

One alternative is to re-configure PyCall to use a different Python
version on your system: set ENV["PYTHON"] to the path/name of the python
executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.

Another alternative is to configure PyCall to use a Julia-specific Python
distribution via the Conda.jl package (which installs a private Anaconda
Python distribution), which has the advantage that packages can be installed
and kept up-to-date via Julia.  As explained in the PyCall documentation,
set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
To install the pyscf module, you can use `pyimport_conda("pyscf", PKG)`,
where PKG is the Anaconda package the contains the module pyscf,
or alternatively you can use the Conda package directly (via
`using Conda` followed by `Conda.add` etcetera).

) <class 'ImportError'>
ImportError('dlopen(/Users/daniel/miniconda3/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.103.dylib\n  Referenced from: /Users/daniel/miniconda3/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so\n  Reason: Incompatible library version: _errors.cpython-36m-darwin.so requires version 106.0.0 or later, but libhdf5.103.dylib provides version 104.0.0',)
  File "/Users/daniel/miniconda3/lib/python3.6/site-packages/pyscf/__init__.py", line 52, in <module>
    from pyscf import lib
  File "/Users/daniel/miniconda3/lib/python3.6/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/Users/daniel/miniconda3/lib/python3.6/site-packages/pyscf/lib/numpy_helper.py", line 29, in <module>
    from pyscf.lib import misc
  File "/Users/daniel/miniconda3/lib/python3.6/site-packages/pyscf/lib/misc.py", line 34, in <module>
    import h5py
  File "/Users/daniel/miniconda3/lib/python3.6/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors

Stacktrace:
 [1] pyimport(::String) at /Users/daniel/.julia/packages/PyCall/l64G5/src/PyCall.jl:547
 [2] top-level scope at /Users/daniel/.julia/dev/ChemInt/draft/pycall_hdf5.jl:10
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] exec_options(::Base.JLOptions) at ./client.jl:296
 [6] _start() at ./client.jl:506
in expression starting at /Users/daniel/.julia/dev/ChemInt/draft/pycall_hdf5.jl:10
```

It is like it changed the path of Python.

**Comment by kleinhenz** [comment] 2020-10-12 16:46
I can reproduce. Very weird. I will look into it.

**Comment by jmert** [comment] 2020-10-12 16:51
> It is like it changed the path of Python.

That's not what I'd read into that error message — I think you're loading incompatible shared libraries. Note that the first line of the python backtrace says `ImportError('dlopen(...) ... Incompatible library version: _errors.cpython-36m-darwin.so requires version 106.0.0 or later, but libhdf5.103.dylib provides version 104.0.0',)`. The python library you loaded wants a newer version of HDF5, but the one being provided in HDF5_jll (which is automatically loaded when you `using HDF5`) provides something just a bit too old.

The short-term workaround is to probably downgrade `pyscf` in version until HDF5_jll's library version is supported. In the longer term, I think we do want to upgrade HDF5.jl to using libhdf5 v1.12, but that's probably secondary to getting a new major release of the Julia package out so I don't know what the timescale on that will be.

**Comment by zyth0s** [comment] 2020-10-12 17:27
Thank you @jmert for the explanation. I had to downgrade HDF5 to 0.12.5. Then it works with pyscf 1.5.3 to 1.7.5.1, which is the latest available to me.

**Comment by jmert** [comment] 2020-10-12 17:36
Do you mean you downgraded HDF5.jl? That's presumably working because v0.12.5 was from before use of HDF5_jll, so you're now just using your OS-provided libhdf5. If that works for you, then you can also just tell the latest HDF5.jl to use your OS-provided libraries instead — see the [Installation Instructions](https://github.com/JuliaIO/HDF5.jl#installation) in the README for how to set an environment variable before building this package (i.e. `Pkg.build("HDF5")`).

**Comment by zyth0s** [comment] 2020-10-12 17:52
Yes. But I do not know which path is using.

**Comment by jmert** [comment] 2020-10-12 17:59
Yes, sorry, looking into this more, it looks like that guess might have been wrong. It looks like HDF5.jl v0.12.5 used a different method of self-produced binaries that what HDF_jll now uses.

It looks like conda h5py and PyPI h5py have different library versions. As best I can tell, conda is shipping libhdf5 v1.10.7 on OSX (https://anaconda.org/anaconda/hdf5), but PyPI (which is what HDF5_jll is using to boostrap it's distribution) is still using libhdf5 v1.10.4. So the reason it just worked for me is that I'd only have PyPI-based (pip installed) python packages which are are self-consistent under v1.10.4 whereas by using Conda, your ecosystem of Python packages wants a newer libhdf5.

(If required for some feature in HDF5.jl...) Instead of downgrading Julia's HDF5.jl, you should be able to ask conda to downgrade the Python packages to a point where `h5py` is using libhdf5 v1.10.4 instead, and then everything should be self consistent.

**Comment by zyth0s** [comment] 2020-10-12 18:02
Your suggestion worked fine. I will close the issue unless you prefer to maintain it.

**Comment by jmert** [comment] 2020-10-12 18:03
Yeah, I was about to close this issue since it's not actually and HDF5.jl bug — just an unfortunate result of non-trivial library interdependencies and library version.

**Closed by jmert** 2020-10-12 18:03 UTC
